"""
CNN model for reconstructing AR maps from the segmentation maps generated by the modified SAM model.
"""

import torch.nn.functional as F
import torch.nn as nn
from .common import LayerNorm2d

class Mask2ARMaps(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 16, kernel_size=7, stride=1, padding='same')
        self.norm1 = LayerNorm2d(16)
        self.conv2 = nn.Conv2d(16, 32, kernel_size=5, stride=1, padding='same')
        self.norm2 = LayerNorm2d(32)
        self.conv3 = nn.Conv2d(32, 16, kernel_size=3, stride=1, padding='same')
        self.norm3 = LayerNorm2d(16)
        self.conv4 = nn.Conv2d(16, 1, kernel_size=1, stride=1, padding='same')

    def forward(self,x):
        """
        Forward pass to reconstruct AR maps from segmentation masks.
        """
        y = F.relu(self.conv1(x), inplace=True)
        y = F.relu(self.conv2(y), inplace=True)
        y = F.relu(self.conv3(y), inplace=True)
        y = self.conv4(y)
        y = y + x # Residual connection
        return y