import torch
from torch import nn
from torch.nn import functional as F

from typing import Any, Dict, List, Tuple

from .image_encoder import ImageEncoderViT
from .mask_decoder import MaskDecoder
from .position_embed import PositionEmbeddingRandom


class SamAR(nn.Module):
    image_format: str = "RGB"

    def __init__(
        self,
        image_encoder: ImageEncoderViT,
        mask_decoder: MaskDecoder,
    ) -> None:
        """
        SAM Model without prompt encoder. It instead uses a learned no-mask embedding in its place.
        
        """
        super().__init__()
        self.image_encoder = image_encoder
        self.mask_decoder = mask_decoder

        self.embed_channel = image_encoder.neck[0].out_channels
        image_embedding_size = image_encoder.img_size // 16
        self.pe_layer = PositionEmbeddingRandom(self.embed_channel//2)
        self.no_mask_embedding = nn.Parameter(torch.randn(1, self.embed_channel, image_embedding_size, image_embedding_size))
    
        nn.init.normal_(self.no_mask_embedding, mean=0.0,std=0.02)

        self.image_embedding_size_tuple = (image_embedding_size, image_embedding_size)

    @property
    def device(self) -> Any:
        return self.no_mask_embedding.device

    def forward(
        self,
        batched_input: List[Dict[str, Any]],
        multimask_output: bool,
    ) -> List[Dict[str, torch.Tensor]]:
        """
        Predicts masks for the input RGB images generated by the CNN.
        """
        input_images = torch.stack([self.preprocess(x["image"]) for x in batched_input], dim=0)
        image_embeddings = self.image_encoder(input_images)

        del input_images

        outputs = []
        sparse_embeddings = torch.empty((1, 0, self.embed_channel), device=self.device)
        image_pe = self.pe_layer(self.image_embedding_size_tuple).unsqueeze(0)
        
        for image_record, curr_embedding in zip(batched_input, image_embeddings):
            dense_embeddings = self.no_mask_embedding

            low_res_masks, iou_predictions = self.mask_decoder(
                image_embeddings=curr_embedding.unsqueeze(0),
                image_pe=image_pe,
                sparse_prompt_embeddings=sparse_embeddings,
                dense_prompt_embeddings=dense_embeddings,
                multimask_output=multimask_output,
            )
            masks = self.postprocess_masks(
                low_res_masks,
                input_size=image_record["image"].shape[-2:],
                original_size=image_record["original_size"],
            )
            
            outputs.append(
                {
                    "masks": masks,
                    "iou_predictions": iou_predictions,
                }
            )
        return outputs

    def postprocess_masks(
        self,
        masks: torch.Tensor,
        input_size: Tuple[int, ...],
        original_size: Tuple[int, ...],
    ) -> torch.Tensor:
        """
        Remove padding and upscale masks to the original image size.

        Arguments:
          masks (torch.Tensor): Batched masks from the mask_decoder,
            in BxCxHxW format.
          input_size (tuple(int, int)): The size of the image input to the
            model, in (H, W) format. Used to remove padding.
          original_size (tuple(int, int)): The original size of the image
            before resizing for input to the model, in (H, W) format.

        Returns:
          (torch.Tensor): Batched masks in BxCxHxW format, where (H, W)
            is given by original_size.
        """
        masks = F.interpolate(
            masks,
            (self.image_encoder.img_size, self.image_encoder.img_size),
            mode="bilinear",
            align_corners=False,
        )
        masks = masks[..., : input_size[0], : input_size[1]]
        masks = F.interpolate(masks, original_size, mode="bilinear", align_corners=False)
        return masks

    def preprocess(self, x: torch.Tensor) -> torch.Tensor:
        """Pad to a square input. Normalization is handled in the dataset."""
        # Pad to image_encoder.img_size (1024x1024)
        h, w = x.shape[-2:]
        padh = self.image_encoder.img_size - h
        padw = self.image_encoder.img_size - w
        x = F.pad(x, (0, padw, 0, padh))
        return x